# Generated by Django 4.2.11 on 2024-04-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='website',
            fields=[
                ('web_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='web/')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
