# Generated by Django 4.2.11 on 2024-04-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portf', '0002_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('art_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='art/')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
