# Generated by Django 4.2.11 on 2024-04-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portf', '0003_art'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Art',
        ),
    ]
