# Generated by Django 5.0.2 on 2024-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portf', '0004_delete_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('art_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='art/')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
