# Generated by Django 4.2.1 on 2024-04-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portf', '0005_art'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='title',
            new_name='descr',
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
