# Generated by Django 4.2.1 on 2024-04-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portf', '0007_alter_art_descr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doh',
            fields=[
                ('art_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='art/')),
            ],
        ),
    ]
