# Generated by Django 4.2.1 on 2024-04-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portf', '0008_doh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doh',
            name='image',
            field=models.ImageField(upload_to='doh/'),
        ),
    ]
