# Generated by Django 4.2.1 on 2024-04-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portf', '0009_alter_doh_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
